// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld2.proto

package grpc.examples.helloworld2;

public final class HelloWorld2ServiceImpl {
  private HelloWorld2ServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloWorld2_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloWorld2_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloWorld2_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloWorld2_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021helloworld2.proto\022\013helloWorld2\"\034\n\014Hell" +
      "oRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007" +
      "message\030\001 \001(\t2K\n\007Greeter\022@\n\010SayHello\022\031.h" +
      "elloWorld2.HelloRequest\032\027.helloWorld2.He" +
      "lloReply\"\000B5\n\031grpc.examples.helloworld2B" +
      "\026HelloWorld2ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloWorld2_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloWorld2_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloWorld2_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_helloWorld2_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloWorld2_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloWorld2_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
